spring.application.name=apirun
server.port=${PORT:8080}

#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://136.115.94.218;databaseName=pos;encrypt=false}
#spring.datasource.username=${SPRING_DATASOURCE_USER:sqlserver}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:!D9t9b9s3}
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# 1. IMPORTANTE: Deja que el Starter de GCP construya la URL por ti. 
# Si dejas la URL vieja (aunque est\u00e9 comentada), aseg\u00farate de que no haya una variable de entorno pis\u00e1ndola.
# No es necesario poner spring.datasource.url si usas las propiedades de abajo.

# 2. Configuraci\u00f3n de Cloud SQL
spring.cloud.gcp.sql.instance-connection-name=project-afb405f8-cf92-4ac1-915:us-central1:sql-server-2022
spring.cloud.gcp.sql.database-name=pos

# 3. Credenciales
spring.datasource.username=sqlserver
spring.datasource.password=!D9t9b9s3

# 4. Driver y Dialecto
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# 5. Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
