spring.application.name=apirun
server.port=${PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://elfacturador.net;databaseName=globalsoft;encrypt=false}
spring.datasource.username=${SPRING_DATASOURCE_USER:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:D3s9rr0ll0}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
