spring.application.name=apirun
server.port=${PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://136.115.94.218;databaseName=pos;encrypt=false}
spring.datasource.username=${SPRING_DATASOURCE_USER:sqlserver}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:!D9t9b9s3}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
